### ISSUE TITLE
最新のお知らせ・データの更新（9〜11例目）

### ISSUE THREAD

**Issue by koogawa** [covid19-miyazaki/covid19#108]
## 更新詳細 / Details of Update
- 9〜11例目のお知らせおよびデータが更新されていたので、サイトにも反映したいです。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/893643/78624626-0bcb8880-78c5-11ea-98d1-2a29f3099880.png)

## 期待する見せ方・挙動 / Expected behavior

![スクリーンショット 2020-04-07 11 33 32](https://user-images.githubusercontent.com/893643/78624640-171eb400-78c5-11ea-8d45-e0a33ac868a9.png)

**Comment by TakaShinoda** [comment]
@koogawa さん
ありがとうございます
やります
