### ISSUE TITLE
お知らせの手動更新を自動にしたい

### ISSUE THREAD

**Issue by koogawa** [covid19-miyazaki/covid19#119]
## 改善詳細 / Details of Improvement
- 現在、公式サイトを元に news.json を手動で更新している。これをスクレイピングで自動化し、プルリクを出すようにしたいです。

#68 のニュース版です

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/893643/78704657-25151900-7947-11ea-9369-f597c850fe17.png)

## 期待する見せ方・挙動 / Expected behavior
- 毎日自動でお知らせをチェックし、プルリクが作成される。

**Comment by koogawa** [comment]
こちらやりたいです！ ✋

**Comment by TakaShinoda** [comment]
@koogawa さん
よろしくお願いします！
