### ISSUE TITLE
「企業の皆様へ」ページの翻訳

### ISSUE THREAD

**Issue by TakaShinoda** [covid19-miyazaki/covid19#123]
## 起こっている問題 / The Problem
- 「企業の皆様へ」ページが英語に対応していない

## スクリーンショット / Screenshot

![スクリーンショット 2020-04-08 10 40 08](https://user-images.githubusercontent.com/45593212/78735363-9d9aca80-7985-11ea-8e25-21b73894f66f.png)

## 期待する見せ方・挙動 / Expected Behavior
- 英語で表記する

## 起こっている問題の再現手段 / Steps to Reproduce
1. 多言語対応選択メニューからEnglishを選択
2. 企業の皆様へを選択 

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by TakaShinoda** [comment]
やります

**Comment by oriverk** [comment]
en.json中に東京版の方の『企業の皆様へ』に対応する翻訳が残ってるので、それらのkeyとvalueごと置き換えて良いかもしれません。※東京版由来は誤訳・変な翻訳を少々含んでるので注意。

**Comment by TakaShinoda** [comment]
わかりました！
