### ISSUE TITLE
お知らせの自動更新プルリクエストを自動マージにしたい

### ISSUE THREAD

**Issue by koogawa** [covid19-miyazaki/covid19#134]
## 改善詳細 / Details of Improvement
- https://github.com/covid19-miyazaki/covid19/pull/120
にてお知らせの更新を自動化し、何日か経ちましたが、正しく動いてるので [auto_merge](https://github.com/apps/auto-merge-bot) に切り替えたいです。
- 毎回誰かがレビューしてマージする手間が省けます

## 期待する見せ方・挙動 / Expected behavior
- プルリクエストに特定のラベルをつけると自動マージされる

例：https://github.com/koogawa/covid19/pull/17

**Comment by koogawa** [comment]
この方針で問題なければやります！ ✋

**Comment by TakaShinoda** [comment]
問題無いと思います
よろしくお願いします
