### ISSUE TITLE
やさしい日本語ページのルビタグ対応

### ISSUE THREAD

**Issue by Morichan** [covid19-miyazaki/covid19#139]
## 改善詳細 / Details of Improvement

やさしい日本語ページのルビ振りを、「<単語>（<フリガナ>）」形式ではなく「<ruby><単語><rp>（</rp><rt><フリガナ></rt><rp>）</rp>」形式 (`<ruby><単語><rp>（</rp><rt><フリガナ></rt><rp>）</rp>`) に変更し、可読性を上げてほしいです。

## スクリーンショット / Screenshot

参考：![https://github.com/tokyo-metropolitan-gov/covid19/pull/2628](https://user-images.githubusercontent.com/5207601/77909426-4a12e780-72c8-11ea-98fc-fc0c79ebe2c1.png)

## 期待する見せ方・挙動 / Expected behavior

https://github.com/tokyo-metropolitan-gov/covid19/pull/2628 によると、TI18nコンポーネントを追加しています。
TI18nコンポーネントでは、vue-i18nコンポーネントをラップすることで、正規表現によりja-Hira.jsonファイルをrubyタグに文字列置換しています。
vue-i18nコンポーネントを呼出している各コンポーネントにおいて、TI18nコンポーネントでラップすることで、実装できると考えます。

## 動作環境・ブラウザ / Environment
不明

**Comment by Morichan** [comment]
#94 での対応の1つとして、とりあえず明日または明後日までに、私が担当してみます。

**Comment by TakaShinoda** [comment]
よろしくお願いします

**Comment by Morichan** [comment]
あともう少しで完成するはずだったルビタグ対応ですが、直前になってタグ形式が変わっていることが発覚しました。

https://github.com/tokyo-metropolitan-gov/covid19/pull/3056

これにより、ここ2日間の作業と僕のやる気が水泡に帰したため、ルビタグ対応はもうしばらくかかります。
何卒、ご容赦ください......
