### ISSUE TITLE
お知らせの項目が多すぎる

### ISSUE THREAD

**Issue by korosuke613** [covid19-miyazaki/covid19#143]
## 改善詳細 / Details of Improvement
- #120 にて、お知らせを自動更新するようになりましたが、全てのお知らせを取得、更新してしまうため、下の画像のように、モバイルからのアクセスだと、お知らせの項目で画面を埋め尽くしてしまいます。
- したがって、[scraping.rb](https://github.com/covid19-miyazaki/covid19/blob/development/scraping.rb)を修正して、例えば4つまでのみのお知らせを取得するようにしたいです。

## スクリーンショット / Screenshot

![97E8C78A-09D8-4330-803A-DAAF471719E3](https://user-images.githubusercontent.com/20027695/79069925-f2836b80-7d0c-11ea-8989-e328b9b55ec8.png)

## 期待する見せ方・挙動 / Expected behavior
- モバイル画面がお知らせで埋め尽くされない。

## 動作環境・ブラウザ / Environment
- iOS
- Safari

**Comment by korosuke613** [comment]
[scraping.rb](https://github.com/covid19-miyazaki/covid19/blob/development/scraping.rb#L11)の下の行を
```ruby
count = dates.length - 1
```

下のように変えれば、ニュースの数を制限できるかも。（４つの場合）
```ruby
count = 4
```

**Comment by Morichan** [comment]
お知らせの項目数ですが、日付ベースでシャットアウトすることで、ある程度の数の項目に絞りつつ、最新の情報を見落とさない様にできる気がします。
いかがでしょうか？

例: 1週間前以前の項目を表示しない様にする

**Comment by korosuke613** [comment]
@Morichan 
> 例: 1週間前以前の項目を表示しない様にする

それをやると、一週間お知らせが更新されないと、最新のお知らせに何も出なくなってしまいますね

**Comment by TakaShinoda** [comment]
私も見た目を統一するなら4つまでとかの方が良いと考えます。

今後感染者が増えて、毎日お知らせが出る場合は4から6にするとかでどうでしょうか？

**Comment by Morichan** [comment]
@korosuke613
最新のお知らせなので、それでも問題無さそうなきがしたのですが......
何か技術的な問題（「無し」などの項目表示ができないなど）とかがあるのでしょうか？

**Comment by korosuke613** [comment]
とりあえず、4つにするコードに変更しました。
プルリク出します。

**Comment by korosuke613** [comment]
@Morichan 
> 何か技術的な問題（「無し」などの項目表示ができないなど）とかがあるのでしょうか？
お知らせを折り畳みできるようにする、みたいなものですか？

**Comment by TakaShinoda** [comment]
> 例: 1週間前以前の項目を表示しない様にする

こちら毎日お知らせがあった場合、以下の画像と同じにになるのでは無いのでようか？
![79069925-f2836b80-7d0c-11ea-8989-e328b9b55ec8](https://user-images.githubusercontent.com/45593212/79070501-57d95b80-7d11-11ea-8ef3-9b45ae5ae0d5.png)

**Comment by Morichan** [comment]
@korosuke613

> > 何か技術的な問題（「無し」などの項目表示ができないなど）とかがあるのでしょうか？
> 
> お知らせを折り畳みできるようにする、みたいなものですか？

いえ、単純に、最新のお知らせ欄の項目が空になると見栄えが悪そうだなぁ、と思ったのと、空になること自体がバグになりそうだなぁ、と思った次第です。

でも確かに、折畳みできると良さそうですね。

**Comment by korosuke613** [comment]
@Morichan @TakaShinoda 

> でも確かに、折畳みできると良さそうですね。

でも、折り畳みの実装はちょっとめんどくさそうなので、とりあえず4つのみにする変更のプルリクを出しました #144

**Comment by Morichan** [comment]
@TakaShinoda

> > 例: 1週間前以前の項目を表示しない様にする
> 
> こちら毎日お知らせがあった場合、以下の画像と同じにになるのでは無いのでようか？

確かにその通りですが、もし仮に項目数で表示を消した場合、1日に5回、新しいお知らせが発信されても表示できないことになります。
「新しいお知らせ」としての機能として成り立たなさそうだなぁ、と思った次第です。

ですが、 @korosuke613 さんの言った様な、折畳みできる機能があれば、新しいお知らせを表示しつつも、表示項目削減が可能かもしれませんね。

**Comment by TakaShinoda** [comment]
@Morichan さん
なるほど！
確かにそうですね
折りたたみ機能の実装方法調べてみます

**Comment by korosuke613** [comment]
@Morichan 
> もし仮に項目数で表示を消した場合、1日に5回、新しいお知らせが発信されても表示できないことになります。

確かにそうですね...
折り畳み機能か、全てのお知らせを表示する機能があれば解決しますね〜

**Comment by korosuke613** [comment]
折り畳み機能誰か実装してください...（他人任せ）

**Comment by Morichan** [comment]
とりあえず、折畳み機能については別チケットとしますか

**Comment by koogawa** [comment]
お知らせに表示する件数については私も課題に思っていました。ご対応いただきありがとうございます！

**Comment by korosuke613** [comment]
こちらのissueについてですが、#146 にて解決しましたので、closeします。
