### ISSUE TITLE
最新のお知らせを折りたためるようにする

### ISSUE THREAD

**Issue by TakaShinoda** [covid19-miyazaki/covid19#146]
## 改善詳細 / Details of Improvement
- 最新のお知らせが多くなり、下の画像のように、モバイルからのアクセスだと、お知らせの項目で画面を埋め尽くしてしまいます。
- #143 で話したように折りたためる(アコーディオンメニュー？)ようにしたいです

## スクリーンショット / Screenshot
![79069925-f2836b80-7d0c-11ea-8989-e328b9b55ec8](https://user-images.githubusercontent.com/45593212/79071178-26628f00-7d15-11ea-8508-01a676c99ab3.png)

## 期待する見せ方・挙動 / Expected behavior
- 折りたためるようにする

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by TakaShinoda** [comment]
やります

**Comment by Morichan** [comment]
すみません、Issue切るのに手間取ってしまいました。

個人的には、こんな感じを想定してます。

![covid19-miyazaki_newest-infomation](https://user-images.githubusercontent.com/20200292/79071253-c3bdc300-7d15-11ea-8ae3-e1e83bd92f53.gif)

参考: https://developer.mozilla.org/ja/docs/Web/HTML/Element/details

**Comment by TakaShinoda** [comment]
@Morichan さん
ありがとうございます
了解しました

**Comment by korosuke613** [comment]
@Morichan 
> 個人的には、こんな感じを想定してます。
これは、デベロッパーツールでやったんですか？
良い感じですね

**Comment by Morichan** [comment]
@korosuke613 

>これは、デベロッパーツールでやったんですか？

そうです、Chromeのデベロッパーツールを使って突貫工事しました。
参考になるかわかりませんが、一応、その時の部分的なHTMLも貼っておきます。

```html
<div class="WhatsNew mb-4" data-v-05427750="">
  <h3 class="WhatsNew-heading">
    <i aria-hidden="true" class="v-icon notranslate WhatsNew-heading-icon mdi mdi-information theme--light" style="font-size:24px"></i>
    最新のお知らせ
  </h3>

  <ul class="WhatsNew-list">
    <li class="WhatsNew-list-item">
      <a href="https://www.pref.miyazaki.lg.jp/kohosenryaku/kenko/hoken/covid19_20200411.html" target="_blank" rel="noopener" class="WhatsNew-list-item-anchor">
        <time datetime="Invalid Date" class="WhatsNew-list-item-anchor-time px-2">
          2020年4月11日
        </time>
        <span class="WhatsNew-list-item-anchor-link">
          新型コロナウイルス感染症患者（第17例目）の発生について（第一報）
          <i aria-hidden="true" class="v-icon notranslate WhatsNew-item-ExternalLinkIcon mdi mdi-open-in-new theme--light" style="font-size:12px"></i>
        </span>
      </a>
    </li>
    <li class="WhatsNew-list-item">
      省略
    </li>
  </ul>

  <details open="">
    <summary>以前のお知らせを確認する</summary>
    <ul class="WhatsNew-list">
      <li class="WhatsNew-list-item">省略</li>
    </ul>
  </details>
</div>
```

**Comment by TakaShinoda** [comment]
最新のお知らせはスクロールバーに変更させていただきたいと思いますがいかがでしょうか？

**Comment by korosuke613** [comment]
> 最新のお知らせはスクロールバーに変更させていただきたいと思いますがいかがでしょうか？

良いと思います。
