### ISSUE TITLE
陽性患者数推移、陽性患者の属性も自動更新したい

### ISSUE THREAD

**Issue by koogawa** [covid19-miyazaki/covid19#152]
## 改善詳細 / Details of Improvement
https://github.com/covid19-miyazaki/covid19/pull/145
により、検査実施人数は自動化することができましたが、
陽性患者数推移、陽性患者の属性の部分は未だ手動更新なので、これらも自動更新したい。

## スクリーンショット / Screenshot

↓囲んだ部分です
![スクリーンショット 2020-04-14 7 51 12](https://user-images.githubusercontent.com/893643/79168447-e38fdc80-7e24-11ea-9f2d-7ae71db650b8.png)

## 期待する見せ方・挙動 / Expected behavior
- 陽性患者数推移、陽性患者の属性の部分が自動更新される

**Comment by koogawa** [comment]
私がやりたいです ✋

**Comment by imabari** [comment]
その後どんなでしょうか？
Pythonですがdata.json作成できます。

**Comment by koogawa** [comment]
すでに実装は完了しております。
実際に陽性患者数が増えた際に動作するかテスト中です。
（これは良いことなのですが、4/11から陽性患者数が増えていないためテストができていません）

**Comment by imabari** [comment]
承知しました。

ご参考までに作成したコードです。
main_summaryまで作成しております。
https://imabari.hateblo.jp/entry/2020/04/16/160314

作成したものと現在のdata.jsonをjsondiffで差分を取ると
dateの部分が異なるのですがわからないためリリース日と同じにしています

http://www.jsondiff.com/

**Comment by koogawa** [comment]
ありがとうございます！
