### ISSUE TITLE
陽性患者数のスクレイピング頻度を改善

### ISSUE THREAD

**Issue by koogawa** [covid19-miyazaki/covid19#153]
## 改善詳細 / Details of Improvement
- https://github.com/covid19-miyazaki/covid19/actions?query=workflow%3A%22Scraping+CI%22 が1時間毎に実行されている
- 1回のジョブ実行に2分かかるとすると、2分 * 24時間 * 30日＝ 1,440分
- 月に使えるジョブ時間は2000分までなので、このスクレイピングだけでほとんど使ってしまう
- 最悪の場合、他のジョブが実行できなくなってしまう

[About billing for GitHub Actions \- GitHub Help](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions)

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/893643/79169077-754c1980-7e26-11ea-9ea1-9f95d7bc25ef.png)

## 期待する見せ方・挙動 / Expected behavior
- https://www.pref.miyazaki.lg.jp/kansensho-taisaku/kenko/hoken/covid19.html は1日に1回ほどしか更新されない
- 6時間毎もしくは12時間毎ぐらいでも良いかもしれません

**Comment by Tatsumi0000** [comment]
修正します．
