### ISSUE TITLE
埋め込みコードコピー時の表示における不具合

### ISSUE THREAD

**Issue by Morichan** [covid19-miyazaki/covid19#173]
## 起こっている問題 / The Problem

indexページの各カードにおける、右下隅の共有ボタンで表示できる埋め込み用コードのクリップボタンを押下すると、「埋め込みコードをコピーしました」表示の右隣に、最終更新日と思われる文字列が表示されてしまいます。

## スクリーンショット / Screenshot

![埋め込みコードコピー時の画面](https://user-images.githubusercontent.com/20200292/79881458-2c025800-842c-11ea-8c4e-92a7da02fab5.gif)

## 期待する見せ方・挙動 / Expected Behavior

- [ ] 「埋め込みコードをコピーしました」表示を、カードの中央に表示すること
- [ ] 「埋め込みコードをコピーしました」表示以外には、新規に表示するオブジェクトが何もないこと

## 起こっている問題の再現手段 / Steps to Reproduce

1. https://covid19-miyazaki.netlify.app/ をブラウザで表示する
2. 任意のカードの右下隅の共有ボタンを押下する
3. 埋め込み用コードのクリップボタンを押下する
4. 「埋め込みコードをコピーしました」表示の右隣に、最終更新日と思われる文字列が表示されてしまう

## 動作環境・ブラウザ / Environment
- Windows 10
- Chrome version 80.0.3987.163（Official Build） （64 ビット）

**Comment by Tatsumi0000** [comment]
私がやります．
