### ISSUE TITLE
陽性患者数グラフにおける前日比が異なる

### ISSUE THREAD

**Issue by Morichan** [covid19-miyazaki/covid19#182]
## 起こっている問題 / The Problem
トップ画面における陽性患者数グラフ表示カードの前日比が、前日との比較ではなく「以前に1人以上陽性患者が存在した日」との比較になっているように見えます。

## スクリーンショット / Screenshot

下図であれば、4月11日が1人／4月10日が0人のため、前日比は +1 人が正しいはずです。
しかし、実際には4月8日の4人と比較しているように見えます。

![image](https://user-images.githubusercontent.com/20200292/80246918-2e70e600-86a8-11ea-8aa9-6d499ca28376.png)

## 期待する見せ方・挙動 / Expected Behavior

前日比を「前日」との比較にする or 前日比という文言を変更する

## 起こっている問題の再現手段 / Steps to Reproduce

トップ画面を開く

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by koogawa** [comment]
本家のソースが陽性患者が存在しない日も毎日データを更新する、という前提の設計になっているようですね。

「以前に1人以上陽性患者が存在した日」との比較
ではなく
前日と比較するように修正してみます。
