### ISSUE TITLE
陽性患者数グラフにおける最新日の棒グラフが半分途欠けている

### ISSUE THREAD

**Issue by Morichan** [covid19-miyazaki/covid19#183]
## 起こっている問題 / The Problem
トップ画面における陽性患者数グラフ表示カードの最新日の棒グラフが、半分欠けています。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/20200292/80247522-26657600-86a9-11ea-9c05-6a4838be71ba.png)

## 期待する見せ方・挙動 / Expected Behavior

グラフ表示を欠けないようにしてほしいです。

## 起こっている問題の再現手段 / Steps to Reproduce

トップ画面を開く

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

Width-Heightの変化は関係なく、一律に欠けて表示されていました。

**Comment by koogawa** [comment]
[chartjs/Chart\.js: Simple HTML5 Charts using the <canvas> tag](https://github.com/chartjs/Chart.js) の設定を変えれば直りそうです。
担当します ✋
