### ISSUE TITLE
自動生成したプルリクエストでactionが発火しない

### ISSUE THREAD

**Issue by korosuke613** [covid19-miyazaki/covid19#194]
## 起こっている問題 / The Problem
- コロナ情報の更新の際に、自動でプルリクエストを出しますが、その時に[actionsで設定したワークフロー](https://github.com/covid19-miyazaki/covid19/blob/development/.github/workflows/pr_test.yml)が起動しません。

## スクリーンショット / Screenshot

![80787188-d0b92e00-8bc0-11ea-97bc-0c2c8934225e](https://user-images.githubusercontent.com/20027695/80812737-81e0b800-8c03-11ea-9b88-3e552c4bbae7.png)
https://github.com/covid19-miyazaki/covid19/pull/192

## 期待する見せ方・挙動 / Expected Behavior
- create-pull-requestを使ってプルリクエストを自動生成した際に、pr_test.ymlが動く。

## 起こっている問題の再現手段 / Steps to Reproduce
create-pull-requestを使ってプルリクエストを作成してください。

参考：
https://github.com/covid19-miyazaki/covid19/pull/192 , https://github.com/covid19-miyazaki/covid19/pull/148

**Comment by korosuke613** [comment]
とりあえず対応します。

**Comment by korosuke613** [comment]
同じ問題について[create-pull-requestのissue](https://github.com/peter-evans/create-pull-request/issues/48)にありました。
どうやら、アクションが他のワークフローをトリガーすることはできないみたいです。
回避策もあるみたいなので、また何かわかったらここに書きます。

**Comment by peter-evans** [comment]
[いくつかの方法](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs)があるんですが、一番簡単なのは[PAT](https://help.github.com/ja/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line)(`repo` scoped)を作って、レポのsecretとして追加して、アクションの`token`に設定します。

```diff
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
+       token: ${{ secrets.PAT }}
        commit-message: 'Update news.json'
        branch: news
        base: master
        labels: auto_merge
        branch-suffix: timestamp
        title: '最新のお知らせ更新'
        body: '公式サイトのお知らせが更新されました。差分を確認してマージしてください。'
```

**Comment by korosuke613** [comment]
Dear @peter-evans 

コメントありがとうございます。(しかも日本語で😭)
[あなたのページ](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork)を読み、4つの方法を実験しました。
私もPATを使う方法が一番楽で便利だと考えます。ただ、自分のアカウントで`approve`, `request changes`できないことが不便です。
なので、あなたのページに載っているように、新しいmachine userを作成し、そのPATを利用する予定です。

"create-pull-request"はとても便利です。"advanced usage"もとても参考になりました。
ありがとうございました🙇😆

↓↓↓↓↓↓↓↓english version(using [DeepL](https://www.deepl.com/home))↓↓↓↓↓↓↓↓

Thank you for your comment. (and in Japanese😭)
I've read [your page](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork) and experimented with four ways.
I also find the PAT method to be the easiest and most convenient. However, it is inconvenient that you cannot `approve`, `request changes` in your account.
So I'm going to create a new machine user and use that PAT, as shown on your page.

"Create-pull-request" is very useful. And "advanced usage" was also very helpful.
Thank you very much🙇😆

**Comment by korosuke613** [comment]
こちらの問題ですが、今日中に対応します。

**Comment by korosuke613** [comment]
![image](https://user-images.githubusercontent.com/20027695/80939297-2dae2180-8e17-11ea-899c-e5d3bc004181.png)

いろいろ試した結果、新たなmachine userを作って、Personal Access Token(PAT)を発行し、create-pull-requestにそのPATを使わせることでワークフローで作ったプルリクエストがワークフローを発火できることがわかりました。

```yaml
    - uses: peter-evans/create-pull-request@v2.7.0
      name: Create Pull Request
      with:
        token: ${{ secrets.BOT_TOKEN }}
```
`secrets`に保存したPATをcreate-pull-requestの`token`に設定することで実現できます。

作成したPATは本リポジトリのsecretに設定しておきます。
