### ISSUE TITLE
最新のお知らせの4月分を削除しても良いのではないでしょうか？

### ISSUE THREAD

**Issue by TakaShinoda** [covid19-miyazaki/covid19#251]
## 改善詳細 / Details of Improvement
- 現在最新のお知らせは4/11で終わっています。最後の感染者が4月に発覚してからそれ以降感染者は出ておらす、先日全員が退院されたという事で、最新のお知らせの感染者情報は削除しても良いのではないでしょうか？その代わりに、5/29に更新された「新しい生活様式の実践へ」と「新型コロナウイルス感染症に関する知事メッセージ」を表示したいと考えます。

## スクリーンショット / Screenshot

![スクリーンショット 2020-05-31 13 17 06](https://user-images.githubusercontent.com/45593212/83344436-eba6cb80-a341-11ea-9c37-ccae69ad7615.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by korosuke613** [comment]
良いと思います！
