### ISSUE TITLE
非公式の文言追記

### ISSUE THREAD

**Issue by TakaShinoda** [covid19-miyazaki/covid19#253]
## 改善詳細 / Details of Improvement
- [本家の宮崎県のサイト](https://www.pref.miyazaki.lg.jp/covid-19/index.html)がリニューアルされ、宮崎県新型コロナウイルス感染症対策特設サイトに名前がなっています。紛らわしいので、本サイトにわかりやすく非公式の文言を追記したいです。

## スクリーンショット / Screenshot

- 現在
![スクリーンショット 2020-05-31 14 04 12](https://user-images.githubusercontent.com/45593212/83344907-09772f00-a348-11ea-9528-ae01c5ebac23.png)

- イメージ
![スクリーンショット 2020-05-31 14 06 59](https://user-images.githubusercontent.com/45593212/83344908-0f6d1000-a348-11ea-8838-eaeb2017b9b5.png)

## 期待する見せ方・挙動 / Expected behavior
- 非公式とわかりやすくしたいです

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by korosuke613** [comment]
けっこう綺麗で良いサイトですね！
必要な情報が集約されているようにも見えますし、もはや本プロジェクトのサイトは必要ないかもしれません👀

![image](https://user-images.githubusercontent.com/20027695/83351918-02b9dd80-a383-11ea-84ef-a441c50fbfdb.png)

**Comment by TakaShinoda** [comment]
本プロジェクトのサイトの方がグラフとかあって見やすいと思います！😄

県のこういうサイトって県庁の人が作ってるんですかね？？

**Comment by korosuke613** [comment]
> 県のこういうサイトって県庁の人が作ってるんですかね？？

詳しくは知りませんが、県がどこかの業者に下請けしてるでしょうね〜

**Comment by TakaShinoda** [comment]
さすがにそうですよね！

ちなみにLighthouseのスコアは本プロジェクトのサイトが勝ってました！
