### ISSUE TITLE
宮崎のイメージカラーにする

### ISSUE THREAD

**Issue by korosuke613** [covid19-miyazaki/covid19#31]
## 改善詳細 / Details of Improvement
- 現在、ベースカラー？を東京都の緑にしているが、この色を宮崎風にしたい。鹿児島とかぶるけどオレンジがいいだろうか？

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/20027695/77723236-3d299600-7033-11ea-8903-9b7a33c2c818.png)

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by TakaShinoda** [comment]
ロゴには黄色，薄いオレンジ，オレンジが使われているけど，県の旗は黄色と緑だね -> [wiki](https://ja.wikipedia.org/wiki/%E5%AE%AE%E5%B4%8E%E7%9C%8C%E6%97%97)

どっちが馴染みあるやろうか...?

**Comment by TakaShinoda** [comment]
ロゴの色やとこんな感じ

<img width="683" alt="スクリーンショット 2020-03-27 14 06 45" src="https://user-images.githubusercontent.com/45593212/77723589-4109e800-7034-11ea-9516-b9411eb29577.png">

**Comment by TakaShinoda** [comment]
`#F08201`
`#FBBD03`
`#FEF104`

**Comment by korosuke613** [comment]
その三色使うのいいかもね！
