### ISSUE TITLE
OGP画像のリンクを書き換える

### ISSUE THREAD

**Issue by korosuke613** [covid19-miyazaki/covid19#33]
## 改善詳細 / Details of Improvement
- 現在、OGP画像のリンクが[東京都](https://stopcovid19.metro.tokyo.lg.jp)のものになっている。これを、[宮崎県のサイト](https://covid19-miyazaki.netlify.com/)に書き換える。(`nuxt.config.js`)

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/20027695/77725371-a4961480-7038-11ea-8bf6-1b6fd6b128b3.png)

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by TakaShinoda** [comment]
これやってる？

**Comment by korosuke613** [comment]
やってない〜

**Comment by TakaShinoda** [comment]
やります！
