### ISSUE TITLE
logo.svgのサイズが大きい

### ISSUE THREAD

**Issue by TakaShinoda** [covid19-miyazaki/covid19#36]
## 起こっている問題 / The Problem
- logo.svgのサイズ(縦横)が大きいためスマホで見ると変

## スクリーンショット / Screenshot

![S__88047618](https://user-images.githubusercontent.com/45593212/77725968-2a668f80-703a-11ea-9c4b-02909bb1c7d9.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- 小さくする

## 動作環境・ブラウザ / Environment
- macOS /  iOS 
- Chrome / Safari

**Comment by TakaShinoda** [comment]
やりますー

**Comment by korosuke613** [comment]
引継ぎます！
