### ISSUE TITLE
"新型コロナウイルス感染症が心配なときに"が東京向けの内容なのでなんとかする

### ISSUE THREAD

**Issue by korosuke613** [covid19-miyazaki/covid19#45]
## 改善詳細 / Details of Improvement
- 「[新型コロナウイルス感染症が心配なときに](https://dev-covid19-miyazaki.netlify.com/flow)」は、多分東京向けの内容だから、宮崎向けに直す。もしくは、このページは非公開にする。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/20027695/77735471-f5643800-704d-11ea-9903-713d6c15535e.png)

## 期待する見せ方・挙動 / Expected behavior
- 宮崎向けになってる
- もしくは、ページが非公開になってる

**Comment by TakaShinoda** [comment]
鹿児島はないから非表示でいいんじゃない？

**Comment by korosuke613** [comment]
おけ！

**Comment by TakaShinoda** [comment]
対応します

**Comment by korosuke613** [comment]
あ、待って、さっき間違ってdevelopmentにあげてしまったので対応済みや

**Comment by korosuke613** [comment]
心配なときに〜を消した · covid19-miyazaki/covid19@6e96fc9

**Comment by TakaShinoda** [comment]
了解
