### ISSUE TITLE
お問い合わせ一覧を宮崎仕様にする

### ISSUE THREAD

**Issue by korosuke613** [covid19-miyazaki/covid19#48]
## 改善詳細 / Details of Improvement
- お問い合わせ一覧を宮崎仕様にする。（https://dev-covid19-miyazaki.netlify.com/contacts）

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/20027695/77736866-4b39df80-7050-11ea-9d39-ccf4e46e91d8.png)

**Comment by TakaShinoda** [comment]
鹿児島版やとお問い合わせ一覧ページないけどどうする？

**Comment by korosuke613** [comment]
今こんな感じ。なくてもいいかも...

![image](https://user-images.githubusercontent.com/20027695/77738458-390d7080-7053-11ea-8fbf-684759ead27f.png)

**Comment by TakaShinoda** [comment]
せっかくならあった方がUXはサイコー
