### ISSUE TITLE
CONTRIBUTING.mdの修正

### ISSUE THREAD

**Issue by korosuke613** [covid19-miyazaki/covid19#56]
## 改善詳細 / Details of Improvement
- 東京向けの説明になっているため、これを修正する

**Comment by TakaShinoda** [comment]
やります

**Comment by TakaShinoda** [comment]
`開発責任者をしています、名前です。何か質問があれば、Slack 等でお気軽に質問してください！`

ここの名前どうする？

**Comment by TakaShinoda** [comment]
学生エンジニアの有志ですとか？

**Comment by TakaShinoda** [comment]
東京も鹿児島も名前のところ関さんって方になってるんやけど変えない方いいんかな？

**Comment by korosuke613** [comment]
いや、多分変えたほうがいいと思う

**Comment by TakaShinoda** [comment]
おけ！

**Comment by korosuke613** [comment]
`開発をしているcovid19-miyazakiです。何か質問があれば、issue 等でお気軽に質問してください！`
とかは？

**Comment by TakaShinoda** [comment]
それいいね！

**Comment by TakaShinoda** [comment]
ごめんdevelopmentブランチにpushしてしまうわ😅
ブランチ切ってなかった

**Comment by TakaShinoda** [comment]
developmentにpushしました

**Comment by korosuke613** [comment]
笑
おけ！
