### ISSUE TITLE
CODE_OF_CONDUCT.mdの修正

### ISSUE THREAD

**Issue by korosuke613** [covid19-miyazaki/covid19#57]
## 改善詳細 / Details of Improvement
- 東京向けになってるため、これを修正する

**Comment by oriverk** [comment]
#48 の『都民→県民』の際の漏れですね。

**Comment by oriverk** [comment]
やります。

**Comment by korosuke613** [comment]
@oriverk さん
貢献していただきありがとうございます！
よろしくお願いします！
