### ISSUE TITLE
サイドバーが英語表示の時，東京都のまま

### ISSUE THREAD

**Issue by Tatsumi0000** [covid19-miyazaki/covid19#62]
## 起こっている問題 / The Problem
- サイドバーのところが，日本語は宮崎県になっているが英語に切り替えると東京都になっている

## スクリーンショット / Screenshot

- 日本語
<img width="235" alt="スクリーンショット 2020-03-28 2 10 02" src="https://user-images.githubusercontent.com/19218690/77781634-451c2100-7099-11ea-9139-f3addf84bf6c.png">

- 英語
<img width="235" alt="スクリーンショット 2020-03-28 2 09 28" src="https://user-images.githubusercontent.com/19218690/77781595-303f8d80-7099-11ea-9bae-6577665845aa.png">

## 期待する見せ方・挙動 / Expected Behavior
- 英語の時も宮崎県にする

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイドバーから`English`を選択

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by TakaShinoda** [comment]
やります

**Comment by Tatsumi0000** [comment]
よろしくお願いします．
