### ISSUE TITLE
やさしいにほんごに対応する

### ISSUE THREAD

**Issue by TakaShinoda** [covid19-miyazaki/covid19#67]
## 起こっている問題 / The Problem
- 多言語選択でやさしいにほんごを選択肢ても優しくない

## スクリーンショット / Screenshot

![スクリーンショット 2020-03-28 23 56 58](https://user-images.githubusercontent.com/45593212/77826019-44929180-7150-11ea-9b41-8799fadb75ee.png)

## 期待する見せ方・挙動 / Expected Behavior
以下をやさしいにほんごにする(スクショ参考)
- サイドメニューバー
- ページタイトル
- (注)の部分

![スクリーンショット 2020-03-28 23 58 42](https://user-images.githubusercontent.com/45593212/77826068-94715880-7150-11ea-9076-3ce103a8c8d2.png)

![スクリーンショット 2020-03-28 23 58 48](https://user-images.githubusercontent.com/45593212/77826071-976c4900-7150-11ea-8049-6b3e36ccb6d3.png)

## 起こっている問題の再現手段 / Steps to Reproduce
1. 多言語対応選択メニューからやさしいにほんごを選択

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by oriverk** [comment]
東京版の『やさしい日本語』表示を参考にしつつ、やります。

**Comment by TakaShinoda** [comment]
@oriverk さん
ありがとうございます。よろしくお願いいたします。

**Comment by oriverk** [comment]
![Untitled](https://user-images.githubusercontent.com/44029144/77842407-aee91780-71cc-11ea-8cea-243f8c6e3729.png)
また、陽性患者の属性のひらがな表示時の『3/17（●月/●日）まで これまでのぜんぶで』について。東京版も同様の[issue #2393](https://github.com/tokyo-metropolitan-gov/covid19/issues/2393)があり、(東京はtransifex上で修正されましたが、）東京版の[pull request #2396](https://github.com/tokyo-metropolitan-gov/covid19/issues/2393)の様に『3/17までのぜんぶで』となるように変更しても大丈夫でしょうか？

**Comment by TakaShinoda** [comment]
はい！大丈夫です。
よろしくお願いいたします
