### ISSUE TITLE
検査数、陽性者数の手動更新を自動にしたい

### ISSUE THREAD

**Issue by korosuke613** [covid19-miyazaki/covid19#68]
## 改善詳細 / Details of Improvement
- 現在、[公式サイト](https://www.pref.miyazaki.lg.jp/kansensho-taisaku/kenko/hoken/covid19.html)を元に[data.json](https://github.com/covid19-miyazaki/covid19/blob/development/data/data.json)を手動で更新することで、検査数、陽性者数を最新のものとしております。正直、手動で毎日更新するのは辛いです。なので、スクレイピングし、毎日自動でプルリクを出すBotがあればいいなと考えます。
- がしかし、宮崎県は毎日検査数を更新しないようです（土日だからか？）。なので、変更がある場合のみ自動でプルリクを出せばいいのかもしれません。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/20027695/77826647-06976c80-7154-11ea-82fc-1d444da9b20d.png)

## 期待する見せ方・挙動 / Expected behavior
- 毎日自動で検査数、陽性者数が最新のものとなる。

**Comment by Tatsumi0000** [comment]
これ自分やりたいのでやらせて下さい。

**Comment by TakaShinoda** [comment]
お願いします

**Comment by korosuke613** [comment]
@Tatsumi0000 
Botがプルリクを送る先ですが、developmentじゃなくてmasterがいいかもしれません。東京都のはmasterにプルリク出してるぽいです。(https://github.com/tokyo-metropolitan-gov/covid19/actions/runs/67114803/workflow)

正確に言うと、development、staging、masterそれぞれにプルリクを出し、[auto_merge_bot](https://github.com/apps/auto-merge-bot)と言うのが自動でmergeしているみたいです。これを真似るかどうかは任せます。
![image](https://user-images.githubusercontent.com/20027695/78006307-ca445600-7377-11ea-83c8-44d8d2cf307b.png)
