### ISSUE TITLE
英語ページにおける宮崎県サイト「新型コロナウイルス感染症について」へのリンクを英語ページにしてほしい

### ISSUE THREAD

**Issue by Morichan** [covid19-miyazaki/covid19#74]
## 改善詳細 / Details of Improvement
[英語版ホームページ](https://covid19-miyazaki.netlify.com/en/) では、左の `Information on the new coronavirus infection in Miyazaki Prefecture` のリンク先として [宮崎県：新型コロナウイルス感染症関連情報（分野別一覧）](https://www.pref.miyazaki.lg.jp/kansensho-taisaku/kenko/hoken/covid19.html) を指定しています。
しかし、このページには英語版の [宮崎県：To People from Overseas: Information on the Coronavirus Disease 2019 (COVID-19) Outbreak](https://www.pref.miyazaki.lg.jp/kohosenryaku/kenko/hoken/covid19_eng.html) が存在します。

## スクリーンショット / Screenshot

![赤枠で囲んだリンク](https://user-images.githubusercontent.com/20200292/77926942-b221f780-72e1-11ea-9a09-1f7ff10da3b6.png)

## 期待する見せ方・挙動 / Expected behavior
英語版ホームページでは、英語版ページに遷移してほしいです。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by korosuke613** [comment]
[vue-i18n](https://kazupon.github.io/vue-i18n/)を使って多言語対応してるので、リンクを言語ごとに変更するってのはどうやればいいんですかね〜

できそうな気はしますので、いづれやります。

**Comment by Morichan** [comment]
[/components/SideNavigation.vue の153行目](https://github.com/covid19-miyazaki/covid19/blob/430f26f6f696127af3cc23b8f108c53040209a0e/components/SideNavigation.vue#L153) のURL文字列を、条件分岐で切替えれば可能そうだと思ったのですが、どうでしょうか？

**Comment by korosuke613** [comment]
たしかに

```typescript
{
          title: this.$t('宮崎県新型コロナウイルス感染症関連情報'),
          link:
            'https://www.pref.miyazaki.lg.jp/kansensho-taisaku/kenko/hoken/covid19.html'
},
```
これを、

```typescript
{
          title: this.$t('宮崎県新型コロナウイルス感染症関連情報'),
          link:
            this.$t('https://www.pref.miyazaki.lg.jp/kansensho-taisaku/kenko/hoken/covid19.html')
},
```

こうすればいけそうな気がしますね

**Comment by Morichan** [comment]
うーん、それでも可能ですけど......

その場合、en.jsonファイルに直接書込むことになってしまいます
URLの文字列とen.jsonは責務が異なるかと

下記のような書き方ができないかなぁ？と思うのですが、僕がJavaScriptにもVue.jsにも詳しくないため、正しい記法がわかりません

```json
{
          title: this.$t('宮崎県新型コロナウイルス感染症関連情報'),
          link:
            if (isJapanese) {
              return 'https://www.pref.miyazaki.lg.jp/kansensho-taisaku/kenko/hoken/covid19.html'
            } else if (isEnglish) {
              return 'https://www.pref.miyazaki.lg.jp/kohosenryaku/kenko/hoken/covid19_eng.html'
            } else {
              return 'https://www.pref.miyazaki.lg.jp/kansensho-taisaku/kenko/hoken/covid19.html'
            }
},
```

if文での分岐もなんか嫌なので、if式みたいな記法（関数型みたいな記法）で、いい感じに書けないでしょうか？

**Comment by Morichan** [comment]
どちらがいいか分からなかったので、とりあえず @korosuke613 さんの提案手法で実装してみます

https://github.com/covid19-miyazaki/covid19/issues/74#issuecomment-606642037

**Comment by korosuke613** [comment]
森さん。

ビルド失敗してたので、Rebertしました。
issueも再openします

https://github.com/covid19-miyazaki/covid19/pull/98
