### ISSUE TITLE
英語ページにおける「陽性患者の属性」の所在地が日本語のまま

### ISSUE THREAD

**Issue by Morichan** [covid19-miyazaki/covid19#79]
## 起こっている問題 / The Problem
英語ページにおける `Details of patients testing positive` （日本語では「陽性患者の属性」）の項目において、地名が日本語のままです。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/20200292/78347524-979a9780-75db-11ea-90d2-5c21ca0022de.png)

## 期待する見せ方・挙動 / Expected Behavior
高千穂町／イギリス／宮崎市を、それぞれ英単語に変えてほしいです。

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページを開く
1. 「言語選択」で英語を選択する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by oriverk** [comment]
やります。

**Comment by oriverk** [comment]
同時に『このサイトについて』の「最新版」の文言と
![abouthissite](https://user-images.githubusercontent.com/44029144/78368669-f0c7f280-75fe-11ea-8437-07fa9255a826.JPG)
『お子様をお持ちの皆様について』の一部文言も英語化しますね。
![tofamilys](https://user-images.githubusercontent.com/44029144/78368674-f291b600-75fe-11ea-9368-fb49768ee3ea.JPG)

**Comment by Tatsumi0000** [comment]
お願いします！

**Comment by TakaShinoda** [comment]
ありがとうございます
お願いします
