### ISSUE TITLE
最新のお知らせ日付ミス

### ISSUE THREAD

**Issue by takeru56** [covid19-miyazaki/covid19#88]
## 起こっている問題 / The Problem
- 最新のお知らせ「新型コロナウイルス感染症患者（4例目）の発生について」の日付が間違っている 
## スクリーンショット / Screenshot

![スクリーンショット 2020-04-04 15 23 59](https://user-images.githubusercontent.com/25771265/78420394-ba838500-7689-11ea-8a2e-e04fd93097e7.png)

## 期待する見せ方・挙動 / Expected Behavior
 `2020/04/03`に修正

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by TakaShinoda** [comment]
ありがとうございます
やります
