### ISSUE TITLE
やさしい日本語ページの必要性、検証、対象者などについて

### ISSUE THREAD

**Issue by Morichan** [covid19-miyazaki/covid19#94]
## 改善詳細 / Details of Improvement

現在、やさしい日本語ページ（以降、やさしい版と呼ぶ）の必要性について、各開発者バラバラであるように感じます。

そこで、プロダクトの方向性を定めるために、やさしい版に対する各開発者の認識合わせをしてみたいのですが、皆さんはどのように考えているのでしょうか？
もし議論などがありましたら、こちらでお話してみてはいかがでしょうか。

## 期待する見せ方・挙動 / Expected behavior

- やさしい版における必要性の検討
- やさしい版の対象者選定
- やさしい版が本当に優しい日本語となっていること検証

## 方針

- [x] ペルソナの策定（[Personas · covid19-miyazaki/covid19 Wiki](https://github.com/covid19-miyazaki/covid19/wiki/Personas)）
- [x] 読みやすさ向上（やさしい日本語ページのルビタグ対応 #139）
- [x] 文章校正（やさしい日本語ページの文章を優しくする #184）
- [x] 導線修正（多言語選択メニューのユーザビリティ向上 #225）

**Comment by Morichan** [comment]
個人的には、やさしい版が優しい日本語となっているか否かについては、疑問に思っています。

- 優しい日本語での表記法にブレがある（言葉の書換え／フリガナ併記など）
- 対象者が不明なため、優しい日本語としての統一が不十分
- 導線が優しくない（日本語ページにおける「多言語対応選択メニュー」から選ぶ必要がある）

逆に言えば、上記をクリアすれば、やさしい版があってもいいのではないか？と考えています。

**Comment by TakaShinoda** [comment]
@Morichan 様
Issueありがとうございます。

私は、[ここ](https://github.com/covid19-miyazaki/covid19/pull/91)にあるようにやさしい日本語は必要だと考えます。

対象者としては、英語はできないけど日本語がちょっとわかる留学生を想定すれば良いと思うのですがみなさんいかがでしょうか？

以下については自分も修正する必要性を感じます

> - 優しい日本語での表記法にブレがある（言葉の書換え／フリガナ併記など）
> - 導線が優しくない（日本語ページにおける「多言語対応選択メニュー」から選ぶ必要がある）

**Comment by korosuke613** [comment]
@Morichan さん。issueの立ち上げありがとうございます。
こちらの[コメント](https://github.com/covid19-miyazaki/covid19/pull/91#discussion_r403645279)でも少し述べましたが、

個人的には、やさしい日本語の必要性はあると考えます。

このやさしい日本語の対象は、児童だけでなく、中途半端に日本語ができる外国人も含んでいると考えています。
なぜなら、東アジア人で日本に来ている方で、英語はできないけど日本語がちょっとわかる（漢字わからない）という方が少なくないと感じているからです（経験談）。宮崎在住のそういう方達には、「やさしい日本語」をあてにする必要があるのではないかと思います。

上記の理由から、完全非対応とするのは悪手だと考えます。

ただ、@Morichan さんが申している

> * 優しい日本語での表記法にブレがある（言葉の書換え／フリガナ併記など）
> * 対象者が不明なため、優しい日本語としての統一が不十分
> * 導線が優しくない（日本語ページにおける「多言語対応選択メニュー」から選ぶ必要がある）

という問題はその通りであると思います。

翻訳関係で大きく貢献していただいてる@oriverk さんも、「中途半端にするくらいならば非対応にするのもありではないか（意訳）」と[申しております。](https://github.com/covid19-miyazaki/covid19/pull/91#discussion_r403476409)

僕は、対応すべきと考えていましたが、少し自分でもちゃんと考えたところ、メンテナンスが難しく中途半端になってしまうならば、非対応にした方が良いかもしれないと思うようになりました。

**Comment by Morichan** [comment]
各問題点については、以下のような解決策があると考えています。

>- 優しい日本語での表記法にブレがある（言葉の書換え／フリガナ併記など）

 => 対象者が決まり次第、方針を定める

>- 対象者が不明なため、優しい日本語としての統一が不十分

 => 主要ペルソナを選定し、性格などを開発者で共有する or 実際のユーザーにレビューを依頼する

>- 導線が優しくない（日本語ページにおける「多言語対応選択メニュー」から選ぶ必要がある）

 => タイトル周辺、または、サイドタイトル周辺に「やさしい日本語（にほんご）で書（か）いたページはこちら」のリンクを貼る

![image](https://user-images.githubusercontent.com/20200292/78468914-f6d0e700-7756-11ea-9d12-670d57b62797.png)

---

決める順序としては、次の通りだと思います。

1. 対象者の選定
1. 導線の修正
1. 表記法ブレの統一化

**Comment by oriverk** [comment]
何も考えずに、サイトトップの『宮崎県 新型コロナウイルス感染症 対策サイト』をやさしい日本語にして、下の様にデザインを崩してましたが、
![image](https://user-images.githubusercontent.com/44029144/78468944-46171780-7757-11ea-8ccd-75ab758401be.png)

『曖昧な表記を避ける。ですます調。』のルールを無視すれば、下の様にもできます。（写真はiPhone 5/SEサイズ
![image](https://user-images.githubusercontent.com/44029144/78468849-61355780-7756-11ea-9cd4-e40a40a850b3.png)

都道府県市町村名やその他の名詞を平仮名付きにするかは議論する必要がありますが、形容詞等は漢字無しでも良いのではとも思います。（例：新（あたら）しい　=>　あたらしい

**Comment by Morichan** [comment]
やさしい版については、必要／不要の2択ではなく、メンテナンス可能／不可能の2択で考えてみませんか？

必要であることは、  @TakaShinoda さん、 @korosuke613 さんが仰っている通りですし、私も認識しているつもりです。
ですが、人員も時間も限られている現在では、コストに見合わない機能は削るべきかと個人的に思います。

そのためには、上記3点（対象者の選定、導線の修正、表記法ブレの統一化）にかかる時間的コストを把握し、それに見合うだけの機能であるとPO（いらっしゃるかどうか知らないのですが）が判断してから、その後の行動に移すとよいかと思います。
いかがでしょうか？

**Comment by korosuke613** [comment]
> 都道府県市町村名やその他の名詞を平仮名付きにするかは議論する必要がありますが、形容詞等は漢字無しでも良いのではとも思います。（例：新（あたら）しい　=>　あたらしい

@oriverk さんのこの案はありだと思います。

それとは別に、 @Morichan さんのいう通り、とりあえず、メンテナンス可能かどうかで考えた方が良いかもしれません。

以下は、対象者の選定、導線の修正、表記法ブレの統一化に関する僕の意見です。

> 対象者の選定
日本語をある程度理解することができるが、漢字がわからない、かつ、英語を理解できない人。

> 導線の修正
サイドタイトル下に「やさしい日本語にする」という感じのリンクを貼る

> 表記法ブレの統一
文章量を減らすために、ですます調というより、丁寧語を使わない。
固有名詞には漢字を使い、ルビを振る。それ以外は極力平仮名のみにする。

**Comment by TakaShinoda** [comment]
確かに、@Morichan さんがおっしゃる通り
メンテナンス可能か、不可能かを決めたいですね

**Comment by oriverk** [comment]
現在、優しい版は公開されており、また非常にマズい翻訳文：『このサイトは宮崎県が作成した』等が残っていたので、議論はさておき修正しました。ただ、サイト右上のロゴ周辺や、陽性患者の属性の表はデザインが崩れたままです。

**Comment by korosuke613** [comment]
メンテナンス可能かどうかの僕の見解を示します。
現時点では、メンテナンスは不可能と考えます。**あくまで、現時点での考えです。**

現在、新しい文章を追加した時、毎回やさしい日本語に追記・変更する必要があります。
英語と違って、原文の漢字にルビをふるという作業をしなければならず、個人的にはとても面倒です。
つまり、申し訳ないのですが、僕はあまり触れたくない部分であり、誰かがやってくれるのを毎回待っている状態です。

したがって、やさしい日本語の更新を苦に思わない方に裁量権を与え、書式なども含めて自由に翻訳していただくのが一番良いと考えております。

なので、そういった方が今後現れず、やさしい日本語が目の上にできたタンコブのママならば、メンテナンスは不可能だと考えます。

**Comment by Morichan** [comment]
> 現時点では、メンテナンスは不可能

率直な意見をありがとうございます。

> 新しい文章追加時に毎回やさしい日本語の追記・変更が必要
> 原文の漢字にルビをふる作業は面倒

これは、その通りだと思います。
また、追記・変更は、現時点では自動化が不可能であり、手間がかかると言わざるをえません。

> やさしい日本語の更新を苦に思わない方に裁量権を与え、書式なども含めて自由に翻訳していただくのが一番良い

であれば、もしよろしければ、私が手を挙げても構いませんか？
1人では流石に大変なので、もう1人でもいらっしゃれば心強いですが

**Comment by Morichan** [comment]
> 現在、新しい文章を追加した時、毎回やさしい日本語に追記・変更する必要があります。

これについては、もう少し考える余地はありそうです。

#97 で考えを書くので、しばらくお待ちください

**Comment by TakaShinoda** [comment]
@Morichan さん
貴重な意見ありがとうございます。
https://github.com/covid19-miyazaki/covid19/issues/97#issuecomment-610877830 拝見しました。

今後 ja.json は触る機会はあまり無いかと考えますがいかがでしょうか？

**Comment by Morichan** [comment]
@TakaShinoda 

> 今後 ja.json は触る機会はあまり無い

そうなのですか？
その場合は、ja.jsonファイルも自動生成するか、言語ファイル編集メンバーだけが触るようにしたほうがいいかもしれませんね

ただその場合（https://github.com/covid19-miyazaki/covid19/issues/97#issuecomment-610877830 での手順と比べて）、変換漏れが発生しやすい可能性があります。
未変換項目があれば、言語ファイル編集メンバーも確認しやすい（各言語ファイルだけを見れば良い）ですが、そうでない場合、機能追加／変更プルリクを全て追う or 機能追加されるたびに全てのページを目視確認する必要がありますから。

**Comment by TakaShinoda** [comment]
自分の認識が間違っているのかもしれないです
他の方はいかがでしょうか？

**Comment by oriverk** [comment]
## 現在の翻訳状況
いま自分が出しているプルリクと昨日のTakaShinodaさんの英語翻訳の結果、現在の宮崎版での未翻訳箇所は恐らくトップ上部の『最新のお知らせ』の箇所(※議論が必要)のみになりました。やさしい版は長文化しやすく、結果デザインが崩れているので、一部修正が必要だと思います。

## ja.json生成自動化について
宮崎版では使用していない、東京版由来のページ等（都営地下鉄利用者数や都庁来庁者数、↓など）のvueファイルが多く残存しています。
![image](https://user-images.githubusercontent.com/44029144/78862201-c5fff300-7a71-11ea-814a-0f5c9f04854b.png)
生成自動化方法は分かりませんが、これらを頭に入れておく必要があると思います。

## 翻訳した時の感じ
やさしい版、英語版ともに翻訳をさせて貰いましたが、変換漏れと思われたものの一部はvue側の文言と言語jsonのキーの齟齬によるもので、私は基本的に翻訳時はja.jsonは参照せずにvueファイルを参照していました。

## 翻訳の手間や漏れの解決案
今後ページ追加があっても、今までの様な翻訳量にはならないと、私は思っており、ja.json自動生成化という事をせずとも、
1. Vue側に文章追加したら、同時にja.jsonの最終行に追加し、他の者へ編集依頼issueを出す。
2. issue受けた人は追加の文をja.jsonからコピーし、en.jsonまたはja-Hira.jsonにkeyへペーストし、翻訳文をvalueに追加。で、プルリク。
といった方法を取れば、翻訳者はja.jsonのみを参照すればよくなるので、翻訳漏れ等も少なくるかと思います。

まとまった文章でなくて、すみません。

**Comment by Morichan** [comment]
@oriverk 

>変換漏れと思われたものの一部はvue側の文言と言語jsonのキーの齟齬によるもので、私は基本的に翻訳時はja.jsonは参照せずにvueファイルを参照していました

まさにその通りで、現在、翻訳作業者は翻訳する際、JSONファイルを正として読まず、実際のサイト（またはVueファイル）を見なければなりません。
これは、手間も時間もかかり、抜け漏れが起こりやすく、イケてないと思います。

また、私が提案している https://github.com/covid19-miyazaki/covid19/issues/97#issuecomment-610877830 は、 @oriverk さんの提案している

> 翻訳の手間や漏れの解決案

と殆ど同じ方法を提案しています。

1箇所だけ見解が異なる点として（あるいは @oriverk さんが見間違いをしている可能性がある点として）、Vueファイル編集者がja.jsonファイルを「手動」で編集すると、他言語ファイル（en.jsonファイルなど）を「自動」で生成してくれるといいな、というものがあります。

これは、ja.jsonファイルの項目と他言語ファイルの項目において、順序の間違いや記載漏れなどを防ぎたいな、と考えているために、自動化であれば防げるのではないか？と思ったために考案しています。

---

話は変わりますが、

> ja.json生成自動化について
> 東京版由来のページ等のvueファイルが多く残存していることを考慮すべき

この点については、別途考える必要があると思うのは、私も同意見です。
そのため、ja.jsonファイルの自動生成については、私もあまり検討してません。
私の中では、あくまで https://github.com/covid19-miyazaki/covid19/issues/97#issuecomment-610877830 案が私の意見であり、 https://github.com/covid19-miyazaki/covid19/issues/94#issuecomment-611243724 案は代替案という立ち位置です。

**Comment by Morichan** [comment]
すみません、本Issueはあくまで優しい日本語ページの必要性を議論する場であり、翻訳方法についてはあまり長く話すべきではありませんね。
議論をごっちゃにしてしまい、すみません。

---

話を戻しますが、修正点3つ（対象者の選定、導線の修正、表記法ブレの統一化）について、ざっと見積もってみました。
私だけではできないので、2名ほど（導線修正1名、統一化1名）手を挙げていただけると幸いです。
また、そのような方が出ない場合は、 https://github.com/covid19-miyazaki/covid19/issues/94#issuecomment-610869135 の通り、メンテナンス不可と判断し、やさしい版ページは消すべきです。

@korosuke613 いかがでしょうか？

- 対象者の選定:
    - 内容: ペルソナを策定（@korosuke613 さんの https://github.com/covid19-miyazaki/covid19/issues/94#issuecomment-609401609 案を採用し、子供と外国人を各1人ずつ）
    - 期日: 明日または今週末
    - 担当: @Morichan 
- 導線の修正:
    - 内容: 多言語対応選択メニューをサイドタイトル直下に移動させ、既定値を「やさしいにほんごにする」にする （@korosuke613 さんの https://github.com/covid19-miyazaki/covid19/issues/94#issuecomment-609401609 案を独自に変更）
    - 期日: 不明
    - 担当: 不明
- 表記法ブレの統一化:
    - 内容: 表記の統一を図るためのIssueを切り、随時プルリクを投げる
    - 期日: 再来週末くらい？
    - 担当: @Morichan , あともう1人

**Comment by korosuke613** [comment]
@Morichan さんのhttps://github.com/covid19-miyazaki/covid19/issues/94#issuecomment-611496833 ですが、

> 修正点3つ（対象者の選定、導線の修正、表記法ブレの統一化）について、ざっと見積もってみました。

良い見積もりかと思います。

> 私だけではできないので、2名ほど（導線修正1名、統一化1名）手を挙げていただけると幸いです。
また、そのような方が出ない場合は、 #94 (comment) の通り、メンテナンス不可と判断し、やさしい版ページは消すべきです。

ただ、現時点で@Morichan さん以外で名乗り出る方がいませんね...
導線の修正でしたら、僕でも可能です。
残り、表記法ブレの統一化を担当していただける方が出ましたら、導線の修正を行います。

**Comment by Morichan** [comment]
> 導線の修正でしたら、僕でも可能

ありがとうございます！
見積りに記載しておきました。

> 表記法ブレの統一化を担当していただける方

手を挙げていただくために、何をする予定かここに書きます。
下記の3点を予定してます。

- やさしい日本語として不適切と考えている単語の抽出
    - ペルソナを参考に、理解できないだろう単語や文章を挙げる
    - 私だけでは独裁的になりやすいため、ここでしっかり複数人での議論がしたい
- 記法の統一化
    - 東京都版などを参考に、やさしい日本語としてのフォーマット（カッコに振り仮名、または、rbタグによる振り仮名の、どちらが良いかなど）を規定する
    - 最終的にはPOの承認を取る必要あり
- 上記をja-Hira.jsonファイルに反映
    - これはただの作業のため、1日あればできると思う
    - @Morichan が作業予定

正直、承認者が欲しいという感じなので、私がほとんど作業しても構いません。

**Comment by Morichan** [comment]
@korosuke613
ペルソナについては、GitHub Wikiを使おうかなと考えています。
よろしいでしょうか？

**Comment by korosuke613** [comment]
@Morichan
了解しました。wikiを有効にします。よろしくお願いしますm(_ _)m

**Comment by Morichan** [comment]
@korosuke613 
ありがとうございます！

とりあえず、やさしい版の主要ペルソナを1名、策定しました。
2名策定する予定でしたが、ペルソナの目標が被る気がしたので、やめました。

ご査収ください。

https://github.com/covid19-miyazaki/covid19/wiki/Personas

**Comment by Morichan** [comment]
全て終わったので、クローズします
結局、自分で全部やってしまいました......

**Comment by korosuke613** [comment]
森さん！ありがとうございました！
お疲れ様でしたm(_ _)m
